playbook_host   : "localhost"
docker_username : "shantibb"
docker_password : "cHq-FP9-GYa-Hqr"

# remote_docker
remote_project_source  : "/root/wallet_project"

# localhost_docker:
localhost_docker_image          : "shantibb/backend:latest"
localhost_dockerfile_path       : "{{ playbook_dir }}/../"
localhost_docker_image_platform : "linux/amd64"
